module:
  hugoVersion:
    min: "0.61.0"
  mounts:
  - source: partials
    target: layouts/partials/tnd-socials
  - source: console
    target: layouts/partials/tnd-socials
  - source: icons
    target: assets/tnd-socials/icons
  imports:
    - path: github.com/theNewDynamic/hugo-module-tnd-icons